### ISSUE TITLE
Suggestion for an additional directive that controls the generated snapshot flags

### ISSUE THREAD

**Issue by rgiot** [EdouardBERGE/rasm#1]
Rasm already has 2 directives that can control some snapshot flags (the crtc and the type of CPC).
I suggest to add a universal directive that can control ANY snapshot flags.

The current workaround is to use rasm to generate the snapshot then an additional tool to modify the snapshot flags. It is error prone and slower even if automated.

The syntax could be: `SETSNA <FLAG> <VALUE>` where `<FLAG>` represents the flag to modify and `<VALUE>` its value.  `SETCRTC` and `SETCPC` could be deprecated with such universal directive.

I have validated such approach with my own playground assembler where this test file is properly assembled while modifying some z80, crtc, and ga registers:
<https://github.com/cpcsdk/rust.cpclib/blob/master/cpclib-asm/tests/snapshot.asm>

A limit of this approach is met when modifying the palette :
`SNASET GA_PAL:0 30 ` is not very much intuitive because of the ink numbering based on hardware color.
The addition of additional functions to make conversions could be useful, such as: 
`SNASET GA_PAL:0 SOFT2HARD_INK(12)`

**Comment by EdouardBERGE** [comment]
agree with syntax (an i'm opened to moar compatibility ;)

SNASET would be OK (no need to keed a SET* syntax)

But for parameter separator Rasm won't use ':' (a comma instead) since it's an instruction separator (internally a new line)

By the way the soft2hard_ink will be a new useful function which may be used anywhere (in a DEFB, ...)

Z80_SP
Z80_A , Z80_B, Z80_BC, ... Z80_R, Z80_I (but not Z80_RI)
what about alternate registers?

GA_PAL
GA_SELECTED_PEN ink
CRTC_REG n,val
CRTC_SELECTED reg

do not remember if this one means this
GA_CONF => ram/rom/mode configuration
GA_RAM => current banking

PPI_CONTROL => in/out

PSG_REG

CPC_TYPE

CRTC_STATE
=> model, hcc, clc, rlc, vtc, hsc, vsc, flags(???)

GA_VSYNC_DELAY
GA_INT_LINE_COUNT
GA_INT_REQUEST

FDC states seems to be useless since it's really partial and unusable

**Comment by rgiot** [comment]
Great news that you are interested in such thing.
Maybe  a comma is also needed between flag and value.
Here is the list of flags i have access to:
https://github.com/cpcsdk/rust.cpclib/blob/3b2744a2241d0d96e711776b4bb4b963e361f478/cpclib-sna/src/flags.rs#L10

They are named based on a former snasphsot manipulation tool of Ramlaid.
Same thing for the : notation for array like flags

**Comment by EdouardBERGE** [comment]
got it, thanks!

**Comment by EdouardBERGE** [comment]
v1.1 with new directive SNASET + doc
