### ISSUE TITLE
Suggestion: add an `opcode` function that returns the value of the given opcode

### ISSUE THREAD

**Issue by rgiot** [EdouardBERGE/rasm#2]
The following sample file illustrates a simple example that works properly with by toy assembler: https://github.com/cpcsdk/rust.cpclib/blob/master/cpclib-asm/tests/opcode.asm and deserves to be available with rasm.

To add this function will allow people that write self-modifying code to not search by which value an opcode is supposed to be replaced:

```z80
 ld a, opcode(pop hl)
 ld (myroutine.regpop), a
```

instead of 
```z80
OPCODE_POP_HL equ 0xe1
...
 ld a,  OPCODE_POP_HL
 ld (myroutine.regpop), a
```

I think such function should return a 32bit value in order to properly manage 4 bytes opcodes

**Comment by EdouardBERGE** [comment]
i think it's too messy in order to be friendly and convenient to use, mostly because opcode may have "any" size

**Comment by cpcitor** [comment]
I love the idea because it allows somehow more "readable"/"maintainable" code in theory.
In practice because opcode can be more than one byte, I understand that it causes complexity and promise of maintainability of the assembler program itself weighs against. ¯\_(ツ)_/¯

**Comment by EdouardBERGE** [comment]
anyone can propose some kind of "best includes for you" like "amstrad_firmware_calls.inc" or "opcodes_bytes.inc"

**Comment by cpcitor** [comment]
> anyone can propose some kind of "best includes for you" like "amstrad_firmware_calls.inc" or "opcodes_bytes.inc"

Well, "anyone" can be me.

You will find on https://github.com/cpcitor/cpc-dev-tool-chain/blob/master/cpclib/cdtc/asminclude/cdtc/z80_syms_for_opcodes_first_byte.s a generated table.

It uses the sdasz80 syntax (because it is part of cpc-dev-tool-chain which existed before rasm), but it is very easy to change all .equ to EQU or whatever you want.

As you will see, it somehow does more than you expected, as it additionally provides names that ensure opcode meaning and visible hex value are always in sync.

**Comment by EdouardBERGE** [comment]
thanks for the opcode file, i puted it in a "resources" folder
